These are the answers to 0x01-python_async_function
